# Generated by Django 4.2.4 on 2023-12-11 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resensi',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
