# Generated by Django 4.2.4 on 2023-12-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resensi', '0002_resensi_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resensi',
            name='published_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
