# Generated by Django 4.2.6 on 2023-10-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembeli', models.TextField(blank=True, null=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
