# Generated by Django 4.2.6 on 2023-10-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='nama_pembeli',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
