# Generated by Django 4.2.4 on 2023-12-11 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231027_1958'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart_checkout', '0002_alter_checkout_alamat_alter_checkout_nama_pembeli'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.IntegerField(default=0)),
                ('list_buku', models.ManyToManyField(to='main.buku')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
