# Generated by Django 4.2.4 on 2023-12-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231027_1958'),
        ('cart_checkout', '0004_belibuku'),
    ]

    operations = [
        migrations.AddField(
            model_name='belibuku',
            name='buku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.buku'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keranjang',
            name='list_buku',
            field=models.ManyToManyField(to='cart_checkout.belibuku'),
        ),
    ]
