# Generated by Django 4.2.6 on 2023-10-26 02:41
from django.core.management import call_command
from django.db import migrations

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "buku.json")

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_remove_buku_language_remove_buku_year_published_and_more'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
